name: SkyBlockPVP
version: 0.0.1
api: [1.13.0, 2.0.0]
author: TKRT Creations Team
main: SkyBlockPVP\Main
commands:
  is:
    Use /is <help>
    description: Comand list of Skyblock
    permission: sbpvp.is.help
permissions:
  sbpvp:
    default: true #when set to Defualt: true, its given For player, no op needed
    description: Allows the user to use the Skyblock Features
    children:
      sbpvp.is:
        default: true #Set for player
        description: Allows the user to use the Skyblock Commands
        children:
          sbpvp.is.help:
            default: true #Set for player
            description: Help command
          sbpvp.is.create:
            default: true
            description: Create an island
          sbpvp.is.delete:
            default: true #Set for Player
            description: Delete your island
          sbpvp.is.invite:
            default: true #Set for player
            description: Invite specified player to your island
            sbpvp.is.warp:
            default: true #Set for player
            description: Warp to specified players island
          sbpvp.is.get:
            default: op #Set ONLY for OPs
            description: Locate a players island
