name: SkyBlockPVP
version: 0.0.1
api: [1.12.0, 1.13.0]
main: SkyBlockPVP\Main
commands:
  is:
    Use /is <help>
    description: Comand list of Skyblock
    permission: sbpvp.is.help
permissions:
  sbpvp:
    default: true #when set to Defualt: true, its given For player, no op needed
    description: Allows the user to use the Skyblock Features
    children:
      sbpvp.is:
        default: true #Set for player
        description: Allows the user to use the Skyblock Commands
        children:
          sbpvp.is.help:
            default: true #Set for player
            description: Allows the player to use the Help Command
          sbpvp.is.create:
            default: true
            description: Allows the player to use the Create Command
          sbpvp.is.get:
            default: op # Set ONLY for OPs
            description: Allows the player to use the find Command
          sbpvp.is.delete:
            default: true # Set for Player
            description: Allows the player to use Delete their island
          sbpvp.is.get.tp:
            default: op # Only For OPs
            description: Allows the player to use Delete their island
