name: SkyBlock Alpha
version: 0.1.0.9
api: [1.13.0]
main: SkyBlock\Main
commands:
  is:
    Uso: /is <help>
    description: Comand list of Skyblock
    permission: is.command.help
permissions:
  is:
    default: true
    description: Allows the user to use the Skyblock Features
    children:
      is.command:
        default: true
        description: Allows the user to use the Skyblock Commands
        children:
          is.command.help:
            default: true
            description: Allows the player to use the Help Command
            is.command.create:
            default: true
            description: Allows the player to use the Create Command
          is.command.find:
            default: op
            description: Allows the player to use the find Command
          is.command.delete:
            default: true
            description: Allows the player to use Delete their island
          is.command.sethome:
            default: true
            description: Allows the player to sethome
          is.command.home:
            default: true
            description: Allows the player to Go to home
        
