#	__   __                 _   _                 	
#	\ \ / /                | \ | |                	
#	 \ V /  ___ _ __   ___ |  \| | _____   ____ _ 	
#	 /   \ / _ \ '_ \ / _ \| . ` |/ _ \ \ / / _` |	
#	/ /^\ \  __/ | | | (_) | |\  | (_) \ V / (_| |	
#	\/   \/\___|_| |_|\___/\_| \_/\___/ \_/ \__,_|	
#                                             
#                                             Creations
# World for skyblock lobby (Islands wont be created here)
# In the quotations put the world name (Spaces aren't supported)
Lobby: "world"
# Language
Lang: "eng"
# Available lanugages:
# spa - Spanish 
# eng - English 
# chi - Traditional Chinese 
# chisi - Simplefied Chinese WIP
# ger - German wIP
# vie - Vietnamese
# More to be added...
